
package com.netjstech.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://soapwsDemo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soapwsDemo.com/", className = "com.netjstech.wsclient.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soapwsDemo.com/", className = "com.netjstech.wsclient.SayHelloResponse")
    @Action(input = "http://soapwsDemo.com/Hello/sayHelloRequest", output = "http://soapwsDemo.com/Hello/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
